[project]
name = "order-service"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.71.0",
    "grpcio-tools>=1.71.0",
    "grpcio-health-checking>=1.71.0",
    "sqlalchemy==2.0.40",
    "alembic==1.15.2",
    "pydantic-settings==2.9.1",
    "dependency-injector==4.46.0",
    "psycopg2-binary==2.9.10",
]

[dependency-groups]
dev = [
    "pytest==8.3.5",
]
