syntax = "proto3";

package user;

service UserService {
  rpc GetUser (GetUserRequest) returns (UserResponse);
  rpc ListUsers (ListUsersRequest) returns (ListUsersResponse);
  rpc CreateUser (CreateUserRequest) returns (UserResponse);
  rpc GetUsersBatch (GetUsersBatchRequest) returns (ListUsersResponse);
}

message GetUserRequest {
  int32 id = 1;
}

message CreateUserRequest {
  string name = 1;
}

message ListUsersRequest {
  int32 page = 1;
  int32 per_page = 2;
  string sort_field = 3;
  string sort_order = 4;
}

message GetUsersBatchRequest {
  repeated int32 ids = 1;
}

message UserResponse {
  int32 id = 1;
  string name = 2;
}

message ListUsersResponse {
  repeated UserResponse users = 1;
}
